const ADAB_PUB_KEY='adab_content_publication_v2', ADAB_SESSION='adab_student_session_v2', ADAB_STUDENT_KEY='adab_students_demo_v2';
const ADAB_CONTENT={
 lessons:['lesson-1-1.html','lesson-1-2.html','lesson-1-3.html','lesson-1-4.html','lesson-1-5.html','lesson-1-6.html','lesson-1-7.html','lesson-1-8.html','lesson-1-9.html','lesson-1-10.html','lesson-2-1.html','lesson-2-2.html','lesson-2-3.html','lesson-2-4.html','lesson-2-5.html','lesson-2-6.html','lesson-2-7.html','lesson-2-8.html','lesson-2-9.html','lesson-3-1.html','lesson-3-2.html','lesson-3-3.html','lesson-3-4.html','lesson-3-5.html','lesson-3-6.html','lesson-3-7.html','lesson-3-8.html','lesson-3-9.html','lesson-3-10.html','lesson-4-1.html','lesson-4-2.html','lesson-4-3.html','lesson-4-4.html','lesson-4-5.html','lesson-4-6.html','lesson-4-7.html','lesson-4-8.html','lesson-4-9.html','lesson-4-10.html','lesson-5-1.html','lesson-5-2.html','lesson-5-3.html','lesson-5-4.html','lesson-5-5.html','lesson-5-6.html','lesson-5-7.html','lesson-5-8.html','lesson-5-9.html','lesson-5-10.html'],
 training:['training-1-1.html','training-1-2.html','training-1-3.html','training-1-4.html','training-1-5.html','training-1-6.html','training-1-7.html','training-1-8.html','training-1-9.html','training-1-10.html','training-2-1.html','training-2-2.html','training-2-3.html','training-2-4.html','training-2-5.html','training-2-6.html','training-2-7.html','training-2-8.html','training-2-9.html','training-3-1.html','training-3-2.html','training-3-3.html','training-3-4.html','training-3-5.html','training-3-6.html','training-3-7.html','training-3-8.html','training-3-9.html','training-3-10.html','training-4-1.html','training-4-2.html','training-4-3.html','training-4-4.html','training-4-5.html','training-4-6.html','training-4-7.html','training-4-8.html','training-4-9.html','training-4-10.html','training-5-1.html','training-5-2.html','training-5-3.html','training-5-4.html','training-5-5.html','training-5-6.html','training-5-7.html','training-5-8.html','training-5-9.html','training-5-10.html'],
 research:['research-1-1.html','research-1-2.html','research-1-3.html','research-1-4.html','research-1-5.html','research-1-6.html','research-1-7.html','research-1-8.html','research-1-9.html','research-1-10.html','research-2-1.html','research-2-2.html','research-2-3.html','research-2-4.html','research-2-5.html','research-2-6.html','research-2-7.html','research-2-8.html','research-2-9.html','research-3-1.html','research-3-2.html','research-3-3.html','research-3-4.html','research-3-5.html','research-3-6.html','research-3-7.html','research-3-8.html','research-3-9.html','research-3-10.html','research-4-1.html','research-4-2.html','research-4-3.html','research-4-4.html','research-4-5.html','research-4-6.html','research-4-7.html','research-4-8.html','research-4-9.html','research-4-10.html','research-5-1.html','research-5-2.html','research-5-3.html','research-5-4.html','research-5-5.html','research-5-6.html','research-5-7.html','research-5-8.html','research-5-9.html','research-5-10.html']};
function reveal(b){const x=b.nextElementSibling;if(x)x.style.display=x.style.display==='block'?'none':'block'} function choose(b,ok){b.parentElement.querySelector('.feedback').textContent=ok?'أحسنت: نحتاج إلى تحليل البناء والدلالة.':'جرّب من جديد: التلخيص وحده لا يجيب عن سؤال نقدي.';}
function adabStatus(){try{const phone=sessionStorage.getItem(ADAB_SESSION);if(!phone)return null;const u=JSON.parse(localStorage.getItem(ADAB_STUDENT_KEY)||'[]').find(s=>s.phone===phone);return u||null}catch(e){return null}}
function adabPub(){try{const v=JSON.parse(localStorage.getItem(ADAB_PUB_KEY)||'null');if(v)return v}catch(e){}return null}
function adabIdFromFile(cat,file){return cat+'-'+file.replace(/^[^-]+-/,'').replace('.html','')}
function adabAllowed(cat,u){if(!u||u.status==='suspended')return false;if(cat==='lessons')return true;if(cat==='research')return u.status==='active'||u.status==='verified';if(cat==='training')return u.status==='verified';return false}
function adabGate(cat){const u=adabStatus();if(!u){return `<div class="access-gate"><div>🔒</div><h2>هذا المحتوى داخل فضاء التلميذ</h2><p>سجّل الدخول إلى فضائك للوصول إلى المحتوى التعليمي.</p><a class="primary-btn" href="../student/index.html">فضاء التلميذ</a></div>`}if(!adabAllowed(cat,u)){return `<div class="access-gate"><div>🧭</div><h2>المحتوى غير متاح لحالة حسابك</h2><p>ستتوسع صلاحياتك بعد توثيق الحساب من طرف الأستاذ.</p><a class="primary-btn" href="../student/index.html">العودة إلى فضائك</a></div>`}return null}
function adabInitAccess(){const path=location.pathname.replace(/\\/g,'/');const parts=path.split('/');const cat=['lessons','training','research'].find(x=>parts.includes(x));if(!cat)return;const file=parts[parts.length-1];const u=adabStatus();const allowed=adabAllowed(cat,u);const pub=adabPub();const isDetail=/^(lesson|training|research)-\d+-\d+\.html$/.test(file);const key=isDetail?adabIdFromFile(cat,file):null;if(isDetail && (!allowed || (pub && pub[key]===false))){const main=document.querySelector('main');if(main){main.innerHTML=adabGate(cat)||`<div class="access-gate"><div>⏳</div><h2>هذا المورد غير منشور بعد</h2><p>سيظهر هنا عندما ينشره الأستاذ.</p><a class="primary-btn" href="../${cat}/index.html">العودة إلى ${cat==='lessons'?'الدروس':cat==='training'?'التدريبات':'البحوث'}</a></div>`;return}}
if(!allowed){const main=document.querySelector('main');if(main){main.innerHTML=adabGate(cat);return}}
// Filter cards by publication and permissions.
const cards=document.querySelectorAll('.card[href]');cards.forEach(card=>{const href=card.getAttribute('href')||'';let targetCat=cat;let m=href.match(/^(lesson|training|research)-(\d+)-(\d+)\.html$/);let am=href.match(/^axis-(\d+)\.html$/);if(m){const prefix=m[1];targetCat=prefix==='lesson'?'lessons':prefix;const id=targetCat+'-'+m[2]+'-'+m[3];if(pub&&pub[id]===false){card.hidden=true;}}else if(am&&pub){const ax=am[1], any=Object.keys(pub).some(id=>id.startsWith(cat+'-'+ax+'-')&&pub[id]!==false);if(!any)card.hidden=true;}});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',adabInitAccess);else adabInitAccess();
