const KEY='adab_students_demo_v2', SESSION='adab_student_session_v2', NOTICES='adab_notices_demo_v2';
const $=id=>document.getElementById(id), modal=$('accountModal'); let mode='login';
const axes=['شعر الحماسة','المنزع العقلي','رسالة الغفران','مغامرة رأس المملوك جابر','حدث أبو هريرة قال'];
function missionContentPath(id){const m=String(id||'').match(/^(lessons|training|research)-(\d+)-(\d+)$/); if(!m)return '../lessons/index.html'; const dir=m[1],prefix=dir==='lessons'?'lesson':dir; return `../${dir}/${prefix}-${m[2]}-${m[3]}.html`;}
function students(){return JSON.parse(localStorage.getItem(KEY)||'[]')}
function notices(){return JSON.parse(localStorage.getItem(NOTICES)||'[]')}
function targetMatch(n,u){return n.target==='all'||n.target===u.status||n.target===('student:'+u.id)}
function renderNotices(u){const box=$('studentNoticeList');if(!box)return;const ns=notices().filter(n=>targetMatch(n,u)).slice(-6).reverse();box.innerHTML=ns.length?ns.map(n=>`<div class="student-notice-item"><b>${n.typeLabel||'تنبيه'}</b><h3>${n.title}</h3><p>${n.text}</p><small>${n.date||''}</small>${n.contentId?`<a href="../${n.contentId.split('-')[0]}/${n.contentId.startsWith('lessons-')?'lesson-':'training-'}${n.contentId.split('-').slice(-2).join('-')}.html">فتح المحتوى ←</a>`:''}</div>`).join(''):'<div class="muted">لا توجد إعلانات جديدة.</div>'}
function saveStudents(v){localStorage.setItem(KEY,JSON.stringify(v))}
function current(){const phone=sessionStorage.getItem(SESSION); return students().find(s=>s.phone===phone)}
function statusLabel(s){return ({new:'مستخدم جديد',active:'مستخدم فعليّ',verified:'مستخدم موثّق',suspended:'موقوف'})[s]||'مستخدم جديد'}
function openModal(next='login'){mode=next; modal.hidden=false; document.body.classList.add('modal-open'); $('modalTitle').textContent=next==='signup'?'إنشاء حساب جديد':'تسجيل الدخول'; $('modalIntro').textContent=next==='signup'?'أنشئ حسابك، ثم ينتظر حسابك التوثيق من الأستاذ.':'أدخل رقم الهاتف وكلمة العبور للدخول إلى فضائك.'; $('nameField').hidden=next!=='signup'; $('schoolField').hidden=next!=='signup'; $('formSubmit').textContent=next==='signup'?'إنشاء الحساب':'دخول'; $('passwordInput').required=true; $('formFeedback').textContent='';}
function close(){modal.hidden=true;document.body.classList.remove('modal-open');$('passwordInput').required=true}
function renderMissionWorkspace(u){const m=u.mission||{};const status=m.status||'new';const title=$('workspaceMissionTitle'),text=$('workspaceMissionText'),link=$('workspaceContentLink'),pill=$('missionStatus'),form=$('missionSubmissionForm'),area=$('missionSubmission'),feedback=$('missionSubmissionFeedback'),review=$('missionReview'),submit=$('submitMission');if(!title)return;title.textContent=m.assigned?m.title:'لا توجد مهمة مسندة حاليًا';text.textContent=m.assigned?m.text:'عندما يسند إليك الأستاذ مهمة ستظهر هنا تعليماتها والمحتوى المرتبط بها.';if(m.contentId){link.href=missionContentPath(m.contentId);link.style.display='inline-block'}else{link.removeAttribute('href');link.style.display='none'}const labels={new:'مهمة جديدة',pending:'في انتظار الإنجاز',submitted:'أرسلته — في انتظار مراجعة الأستاذ',reviewed:'تمت مراجعة الإنجاز'};pill.textContent=labels[status]||'مهمة جارية';pill.className='status-pill '+(status==='reviewed'?'verified':status==='submitted'?'active':'');area.value=m.submission?.text||'';feedback.textContent='';submit.disabled=!m.assigned||status==='submitted'||status==='reviewed';submit.textContent=status==='submitted'?'تم إرسال الإنجاز':status==='reviewed'?'تمت المراجعة':'إرسال الإنجاز إلى الأستاذ';if(m.review?.feedback){review.hidden=false;review.innerHTML=`<h3>ملاحظة الأستاذ</h3><p>${m.review.feedback}</p><small>${m.review.date||''}</small>`}else{review.hidden=true;review.innerHTML=''}}
function submitMission(){const u=current();if(!u||!u.mission?.assigned)return;const text=$('missionSubmission').value.trim();if(!text)return;const list=students(),target=list.find(x=>x.id===u.id);if(!target)return;target.mission=target.mission||{};target.mission.submission={text,date:new Date().toLocaleString('ar-TN')};target.mission.status='submitted';target.mission.progressAwarded=true;target.progress=Math.min(100,(target.progress||0)+20);saveStudents(list);$('missionSubmissionFeedback').textContent='تم إرسال إنجازك إلى الأستاذ. سيظهر له الآن للمراجعة.';showDashboard()}
function showDashboard(){const u=current(); if(!u){$('loginPanel').hidden=false;$('dashboard').hidden=true;return} $('loginPanel').hidden=true;$('dashboard').hidden=false; $('studentName').textContent=u.name; $('profileName').textContent=u.name; $('profileSchool').textContent=u.school; $('profileStatus').textContent=statusLabel(u.status); $('profileStatus').className='status-pill '+u.status; $('profileClass').textContent=u.className||'آداب'; $('researchTool').style.display=(u.status==='active'||u.status==='verified')?'flex':'none'; $('trainingTool').style.display=u.status==='verified'?'flex':'none'; $('missionTitle').textContent=u.mission?.title||'ابدأ ببناء فهمك'; $('missionText').textContent=u.mission?.text||'ابدأ بدرس من المحور الذي تراجعه ثم انتقل إلى التدريب المرتبط به.'; const missionLink=$('missionLink'); if(missionLink){const c=u.mission?.contentId; missionLink.href=c?missionContentPath(c):'../lessons/index.html'; missionLink.textContent=c?'فتح المحتوى المرتبط ←':'متابعة المهمة ←'; missionLink.onclick=()=>{if(c)window.location.assign(missionContentPath(c));};} $('messageCount').textContent=(u.messages||[]).filter(m=>m.from==='teacher'&&!m.read).length; $('progressValue').textContent=(u.progress||0)+'%'; $('progressBar').style.width=(u.progress||0)+'%'; renderMessages(u); renderMessageSection(u);renderNotices(u);renderMissionWorkspace(u);}
function renderMessages(u){const box=$('messagesPreview'); const msgs=u.messages||[]; box.innerHTML=msgs.length?msgs.slice(-3).reverse().map(m=>`<div class="message-item ${m.from==='teacher'?'teacher-msg':''}"><b>${m.from==='teacher'?'الأستاذ':'أنت'}</b><span>${m.text}</span><small>${m.read?'مقروءة':'جديدة'}</small></div>`).join(''):'<p class="muted">لا توجد رسائل بعد.</p>'}
$('openLogin').onclick=()=>openModal('login');$('openSignup').onclick=()=>openModal('signup');$('switchSignup').onclick=()=>openModal('signup');$('forgot').onclick=()=>{$('formFeedback').textContent='إذا نسيت كلمة العبور، يمكنك مراسلة الأستاذ من قسم الرسائل داخل فضائك بعد تسجيل الدخول.'};$('openMessages').onclick=e=>{e.preventDefault();document.getElementById('messages').scrollIntoView({behavior:'smooth'});}; modal.querySelectorAll('[data-close]').forEach(x=>x.onclick=close);
$('logout').onclick=()=>{sessionStorage.removeItem(SESSION);location.reload()};
$('accountForm').onsubmit=e=>{e.preventDefault();let list=students(),phone=$('phoneInput').value.trim();if(mode==='signup'){if(!$('nameInput').value.trim()||!$('schoolInput').value.trim()||!phone||!$('passwordInput').value){$('formFeedback').textContent='يرجى استكمال جميع البيانات.';return}if(list.some(s=>s.phone===phone)){$('formFeedback').textContent='هذا الرقم مرتبط بحساب موجود. جرّب تسجيل الدخول.';return}list.push({id:Date.now(),name:$('nameInput').value.trim(),school:$('schoolInput').value.trim(),phone,password:$('passwordInput').value,status:'new',className:'آداب',progress:0,messages:[],mission:{title:'ابدأ ببناء فهمك',text:'راجع درسًا واحدًا من المحور الذي تختاره ثم عدّ إلى فضائك.'}});saveStudents(list);sessionStorage.setItem(SESSION,phone);close();showDashboard();return}const u=list.find(s=>s.phone===phone&&s.password===$('passwordInput').value);if(!u){$('formFeedback').textContent='رقم الهاتف أو كلمة العبور غير صحيحة.';return}if(u.status==='suspended'){$('formFeedback').textContent='حسابك موقوف حاليًا. تواصل مع الأستاذ.';return}sessionStorage.setItem(SESSION,phone);close();showDashboard()};
function renderMessageSection(u){const box=$('studentMessagesList'),count=$('messageSectionCount'); if(!box||!count)return; const msgs=u.messages||[]; count.textContent=msgs.filter(m=>m.from==='teacher'&&!m.read).length; box.innerHTML=msgs.length?msgs.slice().reverse().map(m=>`<div class="message-item ${m.from==='teacher'?'teacher-msg':''}"><div><b>${m.from==='teacher'?'الأستاذ':'أنت'}</b><small>${m.date||''}</small></div><p>${m.text}</p><span>${m.read?'مقروءة':'جديدة'}</span></div>`).join(''):'<p class="muted">لا توجد رسائل بعد. يمكنك إرسال رسالتك الأولى إلى الأستاذ.</p>';}
$('missionSubmissionForm').onsubmit=e=>{e.preventDefault();submitMission()};
$('studentMessageForm').onsubmit=e=>{e.preventDefault();const u=current();if(!u)return;const text=$('studentMessageInput').value.trim();if(!text)return;let list=students(),target=list.find(s=>s.id===u.id);if(!target)return;target.messages=target.messages||[];target.messages.push({from:'student',text,read:false,date:new Date().toLocaleString('ar-TN')});saveStudents(list);$('studentMessageInput').value='';$('studentMessageFeedback').textContent='تم إرسال رسالتك إلى الأستاذ.';showDashboard();setTimeout(()=>{$('studentMessageFeedback').textContent='';},2500);};
$('markProgress').onclick=()=>{const list=students(),u=current();if(!u)return;u.progress=Math.min(100,(u.progress||0)+10);saveStudents(list);showDashboard()};
showDashboard();

/* ===== اختبارات قصيرة وملاحظات الأستاذ ===== */
const TESTS='adab_tests_demo_v2', NOTES='adab_notes_demo_v2';
const readDemo=k=>JSON.parse(localStorage.getItem(k)||'[]'); const writeDemo=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
function renderStudentTests(u){const box=$('studentTestList');if(!box)return;const arr=readDemo(TESTS).filter(t=>t.published&&(!t.studentId||String(t.studentId)===String(u.id)));$('studentTestCount').textContent=arr.length;box.innerHTML=arr.length?arr.map(t=>{const mine=(t.results||[]).find(r=>String(r.studentId)===String(u.id));return `<div class="admin-test-row"><div><span class="notice-kind">${t.axisLabel}</span><b>${t.title}</b><p>${t.instructions}</p><small>${t.questions.length} أسئلة</small>${mine?`<div class="mission-feedback"><strong>أرسلت إجابتك</strong><small>${mine.date||''}</small></div>`:`<form class="student-test-form" data-id="${t.id}">${t.questions.map((q,i)=>`<div class="test-question"><b>س${i+1}. ${q}</b><textarea class="test-answer" data-q="${i}" required placeholder="اكتب إجابتك..."></textarea></div>`).join('')}<button class="primary-btn" type="submit">إرسال الاختبار</button><div class="form-feedback"></div></form>`}</div></div>`}).join(''):'<div class="empty-state">لا توجد اختبارات منشورة لك حاليًا.</div>';box.querySelectorAll('.student-test-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const id=f.dataset.id,answers=[...f.querySelectorAll('.test-answer')].map(x=>x.value.trim());if(answers.some(x=>!x)){f.querySelector('.form-feedback').textContent='أكمل الإجابات قبل الإرسال.';return}const a=readDemo(TESTS),t=a.find(x=>String(x.id)===id);if(!t)return;t.results=t.results||[];t.results=t.results.filter(r=>String(r.studentId)!==String(u.id));t.results.push({studentId:u.id,studentName:u.name,answers,date:new Date().toLocaleString('ar-TN')});writeDemo(TESTS,a);f.querySelector('.form-feedback').textContent='تم إرسال الاختبار إلى الأستاذ.';renderStudentTests(u)})}
function renderStudentNotes(u){const box=$('studentNotesList');if(!box)return;const arr=readDemo(NOTES).filter(n=>String(n.studentId)===String(u.id));box.innerHTML=arr.length?arr.slice().reverse().map(n=>{const label=({strength:'نقطة قوة',support:'ما يحتاج إلى دعم',next:'الخطوة التالية',general:'ملاحظة عامة'})[n.type]||'ملاحظة';return `<div class="admin-note-row"><span class="note-chip">${label}</span>${n.contextTitle?`<span class="muted">مرتبطة بـ: ${n.contextTitle}</span>`:''}<p>${n.text}</p><small>${n.date||''}</small>${n.reply?`<div class="mission-feedback"><strong>ردّك:</strong><p>${n.reply.text}</p><small>${n.reply.date||''}</small></div>`:`<form class="note-reply-form" data-note="${n.id}"><textarea rows="2" placeholder="يمكنك الرد على ملاحظة الأستاذ..." required></textarea><button class="ghost-btn" type="submit">إرسال الرد</button><div class="form-feedback"></div></form>`}</div>`}).join(''):'<div class="empty-state">ستظهر هنا ملاحظات الأستاذ وتغذيته الراجعة.</div>';box.querySelectorAll('.note-reply-form').forEach(f=>f.onsubmit=e=>{e.preventDefault();const text=f.querySelector('textarea').value.trim();if(!text)return;const a=readDemo(NOTES),n=a.find(x=>String(x.id)===String(f.dataset.note));if(!n)return;n.reply={text,date:new Date().toLocaleString('ar-TN')};writeDemo(NOTES,a);renderStudentNotes(u)})}
const _showDashboardExpanded=showDashboard; showDashboard=function(){_showDashboardExpanded();const u=current();if(u){renderStudentTests(u);renderStudentNotes(u)}};
if(typeof sessionStorage!=='undefined'&&sessionStorage.getItem(SESSION)){setTimeout(()=>showDashboard(),0)}
